import React, { createContext, useState, useContext } from 'react';

// ============================================================
// TRADUCTIONS COMPLÈTES - FRANÇAIS & ENGLISH
// ============================================================

const translations = {
    // ==================== FRANÇAIS ====================
    fr: {
        // ---------- GÉNÉRAL ----------
        app_name: 'StockMedi',
        loading: 'Chargement...',
        error: 'Erreur',
        success: 'Succès',
        login: 'Connexion',
        register: 'Inscription',
        logout: 'Déconnexion',
        email: 'Email',
        password: 'Mot de passe',
        confirm_password: 'Confirmer le mot de passe',
        first_name: 'Prénom',
        last_name: 'Nom',
        phone: 'Téléphone',
        send: 'Envoyer',
        locale: 'fr',
        
        // ---------- NAVIGATION ----------
        nav_dashboard: 'Tableau de bord',
        nav_products: 'Produits',
        nav_sales: 'Ventes',
        nav_reports: 'Rapports',
        nav_employees: 'Employés',
        nav_settings: 'Paramètres',
        nav_subscription: 'Abonnement',
        nav_quotes: 'Devis',
        nav_admin: 'Admin',
        nav_logout: 'Déconnexion',
        forgot_password: 'Mot de passe oublié ?',
        no_account: 'Pas de compte ?',
        create_account: 'Créer un compte',
        already_have_account: 'Déjà un compte ?',
        close_menu: 'Fermer le menu',
        open_menu: 'Ouvrir le menu',
        menu: 'Menu',
        
        // ---------- DASHBOARD ----------
        dashboard_title: 'Tableau de bord',
        dashboard_welcome: 'Bienvenue sur StockMedi. Voici un aperçu de votre activité.',
        hello: 'Bonjour',
        daily_dashboard: 'voici votre tableau de bord du jour',
        sales_today: 'Ventes du jour',
        sales_month: 'Ventes du mois',
        transactions: 'transaction(s)',
        quick_actions: 'Actions rapides',
        add_product: 'Ajouter un produit',
        new_sale: 'Nouvelle vente',
        export_report: 'Exporter rapport',
        top_products: 'Top des produits les plus vendus',
        quantity_sold: 'Quantité vendue',
        revenue: "Chiffre d'affaires",
        view_archives: 'Voir les archives',
        archive_and_reset: 'Archiver et réinitialiser',
        archive_and_reset_success: 'Tableau de bord archivé et réinitialisé avec succès',
        archive_confirm_message: 'Cette action va archiver les données actuelles du tableau de bord et réinitialiser les compteurs. Les données archivées restent consultables. Confirmez-vous ?',
        yes_archive: 'Oui, archiver',
        product: 'Produit',
        my_sales_today: 'Mes ventes aujourd\'hui',
        manage_products: 'Gérer les produits',
        stock_entry: 'Entrée de stock',
        no_quick_actions: 'Aucune action rapide disponible. Contactez votre administrateur.',
        migrate_products_confirm: 'Vous avez {{count}} produit(s) non rattaché(s) à un établissement. Voulez-vous les associer à "{{name}}" ?',

        // ---------- ARCHIVES ----------
        dashboard_archives: 'Archives du tableau de bord',
        archives_subtitle: 'Consultez l\'historique des réinitialisations',
        year: 'Année',
        month: 'Mois',
        all_years: 'Toutes les années',
        all_months: 'Tous les mois',
        period: 'Période',
        archive_date: 'Date d\'archivage',
        type: 'Type',
        sales_period: 'Ventes (période)',
        manual: 'Manuel',
        auto: 'Auto',
        no_archives_found: 'Aucune archive trouvée',
        previous: 'Précédent',
        next: 'Suivant',
        page: 'Page',
        delete_permanently: 'Supprimer définitivement',
        confirm_delete_archive: 'Êtes-vous sûr de vouloir supprimer définitivement l\'archive',
        action_irreversible: 'Cette action est irréversible.',
        yes_delete: 'Oui, supprimer',
        error_loading_archives: 'Erreur lors du chargement des archives',
        archive_deleted_success: 'Archive supprimée définitivement',
        error_deleting_archive: 'Erreur lors de la suppression',
        
        // ---------- ALERTES ----------
        click_to_view: 'Cliquez pour voir',
        alerts: 'Alertes importantes',
        out_of_stock: 'Rupture',
        low_stock: 'Stock faible',
        expiring_soon: 'Expire bientôt',
        expired: 'Expiré',
        out_of_stock_products: 'produit(s) en rupture de stock',
        low_stock_products: 'produit(s) en stock faible',
        expiring_soon_products: 'produit(s) expirent dans les 30 jours',
        expired_products: 'produit(s) sont expirés',
        
        // ---------- PRODUITS ----------
        products_title: 'Gestion des produits',
        products_subtitle: 'Gérez votre stock de produits médicaux',
        new_product: 'Nouveau produit',
        search: 'Recherche',
        search_placeholder: 'Nom, générique, code-barres...',
        category: 'Catégorie',
        all_categories: 'Toutes',
        stock_status: 'Statut stock',
        all_status: 'Tous',
        reset: 'Réinitialiser',
        name: 'Nom',
        category_col: 'Catégorie',
        stock: 'Stock',
        purchase_price: "Prix d'achat",
        selling_price: 'Prix de vente',
        margin: 'Marge',
        expiration: 'Expiration',
        actions: 'Actions',
        no_products: 'Aucun produit trouvé',
        edit: 'Modifier',
        delete: 'Supprimer',
        confirm_delete: 'Voulez-vous vraiment archiver le produit',
        product_name: 'Nom du produit',
        generic_name: 'Nom générique',
        manufacturer: 'Fabricant',
        batch_number: 'Numéro de lot',
        barcode: 'Code-barres',
        quantity: 'Quantité',
        unit: 'Unité',
        reorder_point: "Seuil d'alerte",
        location: 'Emplacement',
        manufacturing_date: 'Date de fabrication',
        expiration_date: "Date d'expiration",
        description: 'Description',
        prescription_required: 'Ordonnance requise',
        margin_info: 'Marge bénéficiaire',
        sell_at_loss: 'VENTE À PERTE',
        margin_zero: 'MARGE NULLE',
        margin_zero_confirm: 'Marge nulle. Confirmer ?',
        add: 'Ajouter',
        save: 'Enregistrer',
        product_created: 'Produit créé avec succès',
        product_updated: 'Produit modifié avec succès',
        product_deleted: 'Produit archivé avec succès',
        product_name_required: 'Le nom du produit est requis',
        purchase_price_required: "Le prix d'achat est requis",
        selling_price_required: 'Le prix de vente est requis',
        expiration_date_required: "La date d'expiration est requise",
        purchase_price_zero: "Le prix d'achat ne peut pas être nul",
        manufacturing_after_expiration: 'La date de fabrication ne peut pas être postérieure à la date d\'expiration',
        expired_confirm: 'La date d\'expiration est déjà dépassée. Voulez-vous continuer ?',
        no_products_search: 'Aucun produit ne correspond à votre recherche',
        in_stock: 'En stock',
        dci: 'DCI',
        princeps: 'Princeps',
        generique: 'Générique',
        medication: 'Médicament',
        medical_device: 'Dispositif médical',
        parapharmacy: 'Parapharmaceutique',
        food_supplement: 'Complément alimentaire',
        vitamin: 'Vitamine',
        medical_service: 'Prestation médicale',
        service_type: 'Type de prestation',
        blood_pressure: 'Prise de tension',
        weight: 'Prise de poids',
        height: 'Prise de taille',
        heart_rate: 'Prise de rythme',
        glycemia_test: 'Test de glycémie rapide',
        vaccination: 'Vaccination',
        tablets: 'Comprimés',
        capsules: 'Capsules',
        blisters: 'Plaquettes',
        ampoules: 'Ampoules',
        boxes: 'Boîtes',
        box: 'Boîte(s)',
        bottle: 'Bouteille',
        fabricant: 'Fabricant',
        lot_number: 'N° de lot',
        lot: 'Lot',
        barcode_label: 'Code-barres',
        location_label: 'Emplacement',
        unit_label: 'Unité',
        alert_threshold: 'Seuil d\'alerte',
        purchase_price_label: 'Prix d\'achat',
        selling_price_label: 'Prix de vente',
        manufacturing_date_label: 'Date de fabrication',
        expiration_date_label: 'Date d\'expiration',
        description_label: 'Description',
        prescription_required_label: 'Nécessite une ordonnance',
        lower_than: 'inférieur au',
        profit: 'Bénéfice',
        select_establishment: 'Veuillez sélectionner un établissement',
        dci_required: 'La DCI est requise',
        na: 'N/A',
        select: 'Sélectionner',
        consumable: 'Consommable',
        
        // ---------- VENTES ----------
        sales_title: 'Point de vente',
        sales_subtitle: 'Enregistrez vos ventes rapidement',
        history: 'Historique des ventes',
        back_to_pos: 'Retour au point de vente',
        search_product: 'Rechercher un produit',
        available_products: 'Produits disponibles',
        cart: 'Panier',
        empty_cart: 'Le panier est vide',
        customer: 'Client',
        client: 'Client',
        customer_name: 'Nom du client',
        customer_phone: 'Téléphone',
        prescription_number: 'N° Ordonnance',
        subtotal: 'Sous-total',
        discount: 'Remise',
        tax: 'TVA (18%)',
        total: 'Total',
        payment_method: 'Mode de paiement',
        cash: 'Espèces',
        card: 'Carte bancaire',
        mobile_money: 'Mobile Money',
        mixed: 'Mixte',
        validate: 'Valider la vente',
        clear: 'Vider',
        confirm_sale: 'Confirmer la vente',
        confirm_message: 'Confirmez-vous cette vente ?',
        items: 'Articles',
        payment: 'Paiement',
        status: 'Statut',
        validated: 'Validée',
        cancelled: 'Annulée',
        prescription_required_error: 'Ce produit nécessite une ordonnance.',
        stock_insufficient: 'Stock insuffisant',
        max_available: 'Maximum disponible',
        sale_success: 'Vente enregistrée avec succès !',
        search_hint: 'Saisissez au moins 2 caractères',
        customer_name_placeholder: 'Nom du client (optionnel)',
        customer_phone_placeholder: 'Téléphone (optionnel)',
        prescription_placeholder: 'Si applicable',
        sale_number: 'N° vente',
        date: 'Date',
        no_sales: 'Aucune vente enregistrée',
        receipt: 'Reçu',
        view_receipt: 'Voir le reçu',
        print: 'Imprimer',
        download: 'Télécharger',
        share: 'Partager',
        close: 'Fermer',
        thank_you: 'Merci de votre visite !',
        client_comptant: 'Client comptant',
        seller: 'Vendeur',
        enterprise_plan_promo: '💡 Pour gérer plusieurs établissements, passez au plan',
        search_placeholder_sales: 'Nom, générique, code-barres...',
        no_products_in_establishment: 'Aucun produit trouvé dans cet établissement',
        no_permission_sales: 'Vous n\'avez pas la permission de créer des ventes',
        quantity_short: 'Qté',
        price_short: 'Prix',
        total_short: 'Total',
        designation: 'Désignation',
        unit_price_short: 'P.U.',
        created_on: 'Créé le',
        by: 'par',
        not_provided: 'Non renseigné',
        view_sales: 'Voir les ventes',
        
        // ---------- DEVIS / PROFORMAS ----------
        quotes_title: 'Devis / Proformas',
        quotes_subtitle: 'Gérez vos devis et convertissez-les en ventes',
        new_quote: 'Nouveau devis',
        quote_details: 'Détail du devis',
        create_quote: 'Créer un devis pour votre client',
        generate_quote: 'Générer le devis',
        quote_number: 'N° Devis',
        quote_date: 'Date',
        quote_valid_until: 'Valable jusqu\'au',
        quote_validity: 'Ce devis est valable 7 jours',
        quote_thank_you: 'Merci de votre confiance',
        quote_converted: 'Ce devis a été converti en vente le',
        quote_converted_on: 'Ce devis a été converti en vente le',
        convert_to_sale: 'Convertir en vente',
        convert_confirm: 'Êtes-vous sûr de vouloir convertir ce devis en vente ? Les stocks seront déduits.',
        convert: 'Convertir',
        quote_converted_success: 'Devis converti en vente avec succès !',
        quote_deleted_success: 'Devis supprimé avec succès',
        quote_delete_confirm: 'Êtes-vous sûr de vouloir supprimer le devis',
        delete_quote: 'Supprimer le devis',
        cannot_convert: 'Ce devis ne peut pas être converti en vente',
        quote_status_draft: 'Brouillon',
        quote_status_sent: 'Envoyé',
        quote_status_converted: 'Converti',
        quote_status_expired: 'Expiré',
        quote_status_cancelled: 'Annulé',
        all_quotes: 'Liste des devis',
        no_quotes: 'Aucun devis trouvé',
        quote_items: 'Articles',
        quote_client: 'Client',
        quote_notes: 'Notes',
        quote: 'Devis',
        view: 'Voir',
        error_loading_quote: 'Erreur lors du chargement du devis',
        error_loading_quotes: 'Erreur lors du chargement des devis',
        error_creating_quote: 'Erreur lors de la création du devis',
        error_converting: 'Erreur lors de la conversion',
        quote_not_found: 'Devis non trouvé',
        notes_placeholder: 'Notes...',
        
        // ---------- RAPPORTS ----------
        reports_title: 'Rapports et exportations',
        reports_subtitle: 'Exportez vos données en PDF ou Excel',
        inventory: "Rapport d'inventaire",
        inventory_desc: "Exportez la liste complète de vos produits avec les stocks, prix et dates d'expiration.",
        sales_report: 'Rapport des ventes',
        sales_desc: "Exportez l'historique de vos ventes avec détails par transaction.",
        download_pdf: 'Télécharger PDF',
        download_excel: 'Télécharger Excel',
        start_date: 'Date début',
        end_date: 'Date fin',
        leave_empty: 'Laissez vide pour exporter toutes les ventes',
        info_title: 'Informations sur les exports',
        info_pdf: 'Format optimisé pour l\'impression et l\'archivage',
        info_excel: 'Format modifiable avec feuille de résumé et données détaillées',
        info_filter: 'Les rapports de ventes peuvent être filtrés par période',
        info_currency: 'Tous les montants sont affichés en',
        download_success: 'Fichier téléchargé avec succès',
        download_error: 'Erreur lors du téléchargement',
        reports_filtered_by_establishment: 'Les rapports seront générés pour l\'établissement sélectionné.',
        filterable_by_establishment: 'Filtrable par établissement',
        reports_filterable_by_establishment: 'Rapports filtrables par établissement',

        // ---------- EMPLOYÉS ----------
        employees_title: 'Gestion des employés',
        employees_subtitle: 'Gérez les comptes de vos employés et leurs permissions',
        add_employee: 'Ajouter un employé',
        no_employees: 'Aucun employé. Cliquez sur "Ajouter un employé" pour commencer.',
        employee: 'Employé',
        contact: 'Contact',
        discipline: 'Discipline',
        permissions: 'Permissions',
        active: 'Actif',
        inactive: 'Inactif',
        first_name_placeholder: 'Viviane Boma',
        last_name_placeholder: 'Onivogui',
        email_placeholder: 'vivianeboma@email.com',
        phone_placeholder: '620000000',
        discipline_label: 'Discipline / Spécialité',
        pharmacist: 'Pharmacien',
        doctor: 'Médecin',
        nurse: 'Infirmier',
        assistant: 'Assistant',
        accountant: 'Comptable',
        other: 'Autre',
        permissions_label: 'Permissions',
        manage_stock: 'Gestion stock',
        make_sales: 'Ventes',
        view_reports: 'Rapports',
        view_dashboard: 'Voir tableau de bord',
        view_products: 'Voir produits',
        cancel_sales: 'Annuler ventes',
        manage_employees: 'Gérer employés',
        manage_establishments: 'Gérer établissements',
        manage_settings: 'Paramètres',
        password_mismatch: 'Les mots de passe ne correspondent pas',
        password_too_short: 'Le mot de passe doit contenir au moins 6 caractères',
        employee_added: 'Employé ajouté avec succès',
        employee_updated: 'Employé modifié avec succès',
        employee_deleted: 'Employé supprimé avec succès',
        email_cannot_change: "L'email ne peut pas être modifié",
        activate: 'Activer',
        deactivate: 'Désactiver',
        employee_limit_reached: 'Limite d\'employés atteinte. Passez à un plan supérieur.',
        establishments: 'Établissements',
        all_establishments: 'Tous',
        establishments_access: 'Accès aux établissements',
        establishments_hint: 'Si aucun établissement n\'est sélectionné, l\'employé aura accès à tous.',
        
        // ---------- PARAMÈTRES ----------
        settings_title: 'Paramètres',
        settings_subtitle: 'Configurez votre entreprise et votre compte utilisateur',
        company: 'Entreprise',
        profile: 'Mon profil',
        company_info: "Informations de l'entreprise",
        company_name: "Nom de l'entreprise",
        company_name_placeholder: 'Pharmacie Centrale',
        company_phone: 'Téléphone entreprise',
        company_phone_placeholder: '620000000',
        company_email: 'Email',
        address: 'Adresse',
        city: 'Ville',
        city_placeholder: 'Conakry',
        street: 'Rue',
        postal_code: 'Code postal',
        country: 'Pays',
        preferences: 'Préférences',
        currency: 'Devise',
        language: 'Langue',
        tax_rate: 'Taux de TVA (%)',
        invoice_prefix: 'Préfixe facture',
        expiration_alerts: 'Alertes expiration (jours)',
        batch_tracking: 'Suivi des lots',
        prescription_default: 'Ordonnance obligatoire par défaut',
        personal_info: 'Informations personnelles',
        role: 'Rôle',
        update_profile: 'Mettre à jour le profil',
        change_password: 'Changer le mot de passe',
        current_password: 'Mot de passe actuel',
        new_password: 'Nouveau mot de passe',
        save_success: 'Paramètres enregistrés avec succès',
        profile_updated: 'Profil mis à jour avec succès',
        password_changed: 'Mot de passe modifié avec succès',
        current_password_required: 'Veuillez saisir votre mot de passe actuel',
        new_password_required: 'Veuillez saisir un nouveau mot de passe',
        owner: 'Propriétaire',
        super_admin: 'Super Admin',
        role_employee: 'Employé',
        expiration_hint: 'Alerte X jours avant expiration',
        logo_url: 'Logo (URL)',
        logo_url_placeholder: 'https://...',

        // ---------- INSCRIPTION & CGU ----------
        accept_terms: 'J\'accepte les',
        terms_of_use: 'conditions d\'utilisation',
        must_accept_terms: 'Vous devez accepter les conditions d\'utilisation',

        // ---------- SUPPRESSION DE COMPTE (RGPD) ----------
        delete_account: 'Supprimer mon compte',
        delete_account_warning: 'La suppression de votre compte est définitive et irréversible.',
        delete_account_confirm: 'Je comprends que cette action est définitive',
        delete_account_password: 'Entrez votre mot de passe pour confirmer',
        delete_account_success: 'Votre compte a été supprimé avec succès',
        delete_account_error: 'Mot de passe incorrect',
        danger_zone: 'Zone dangereuse',
        inactivity_deletion_subject: 'Votre compte StockMedi sera bientôt supprimé',
        inactivity_deletion_body: 'Votre compte est inactif depuis {months} mois. Il sera supprimé dans {days} jours.',
        deletion_pending: 'Une demande de suppression est en cours.',
        deletion_scheduled: 'Votre compte sera supprimé le',
        cancel_deletion: 'Annuler la demande',
        request_deletion: 'Demander la suppression de mon compte',
        confirm_deletion: 'Confirmer',
        deletion_delay_warning: 'Votre compte sera supprimé dans 7 jours. Vous pouvez annuler avant ce délai.',
        
        // ---------- ABONNEMENT ----------
        subscription_title: 'Abonnement',
        subscription_subtitle: 'Gérez votre abonnement et choisissez le plan adapté à vos besoins',
        current_subscription: 'Votre abonnement actuel',
        valid_until: 'Valable jusqu\'au',
        days_remaining: 'Jours restants',
        auto_renew: 'Renouvellement automatique',
        cancel: 'Annuler',
        choose_plan: 'Choisissez votre plan',
        free: 'Gratuit',
        trial: 'Commencer l\'essai',
        subscribe: 'Souscrire',
        current_plan: 'Plan actuel',
        products_max: 'produits max',
        employees_max: 'employés max',
        cancel_confirm: 'Annuler votre abonnement ? Vous pourrez continuer jusqu\'à la fin de la période.',
        payment_error: 'Erreur lors de l\'initialisation du paiement',
        days: 'jours',
        redirecting: 'Redirection...',
        stock_basic: 'Gestion de stock basique',
        stock_advanced: 'Gestion de stock avancée',
        sales_basic: 'Ventes basiques',
        sales_advanced: 'Ventes avancées + panier',
        reports_basic: 'Rapports basiques',
        reports_advanced: 'Rapports avancés + graphiques',
        pdf_exports: 'Export PDF/Excel',
        employees_management: 'Gestion des employés',
        advanced_stats: 'Statistiques avancées',
        multiple_locations: 'Multi-emplacements',
        api_access: 'API Access',
        priority_support: 'Support prioritaire',
        local_payment_title: 'Demande de paiement local',
        full_name: 'Nom complet',
        full_name_placeholder: 'Dr. Viviane Boma',
        preferred_contact: 'Mode de contact préféré',
        additional_message: 'Message (optionnel)',
        additional_message_placeholder: 'Informations supplémentaires...',
        payment_info_title: 'Fonctionnement du paiement local',
        payment_info_description: 'Après validation de votre demande, vous recevrez les instructions pour effectuer le paiement par Mobile Money. Votre abonnement sera activé qu\'après réception du paiement.',
        mobile_money_numbers: 'Numéros Mobile Money',
        submit_request: 'Envoyer la demande',
        payment_request_success: 'Votre demande a été envoyée avec succès ! Vous recevrez un email de confirmation.',
        error_submitting: 'Erreur lors de l\'envoi de la demande',
        request_received: 'Demande reçue !',
        request_received_description: 'Merci. Votre demande a bien été enregistrée. Vous recevrez un email de confirmation dans quelques instants.',
        local_payment_option: 'Option de paiement local',
        local_payment_description: 'Vous manquez de carte pour payer via Stripe? Payez par Mobile Money.',
        pay_by_mobile_money: 'Payer par Mobile Money',
        
        // ---------- ÉTABLISSEMENTS ----------
        establishments_title: 'Établissements',
        establishments_subtitle: 'Gérez vos pharmacies, cliniques et points de vente',
        new_establishment: 'Nouvel établissement',
        transfer_stock: 'Transférer du stock',
        establishment_name: 'Nom de l\'établissement',
        establishment_type: 'Type d\'établissement',
        pharmacy: 'Pharmacie',
        clinic: 'Clinique',
        hospital: 'Hôpital',
        lab: 'Laboratoire',
        warehouse: 'Entrepôt',
        establishment_created: 'Établissement créé avec succès',
        establishment_updated: 'Établissement modifié avec succès',
        establishment_deleted: 'Établissement supprimé avec succès',
        establishment: 'Établissement',
        loading_establishments: 'Chargement des établissements...',
        no_establishments_create_one: 'Aucun établissement. Créez-en un dans les paramètres.',
        establishment_count: 'établissement(s)',
        establishment_name_placeholder: 'Pharmacie du Centre',
        street_placeholder: 'Kaloum, Boulevard Louis Lansana Béavogui',
        products_migrated_success: 'Produits migrés avec succès',
        error_migrating_products: 'Erreur lors de la migration des produits',
        restock_transfer_etc: 'Réapprovisionnement, mutation, etc.',

        // ---------- TRANSFERT DE STOCK ----------
        transfer: 'Transférer',
        transfer_success: 'Transfert effectué avec succès',
        error_transfer: 'Erreur lors du transfert',
        error_loading_data: 'Erreur chargement des données',
        fill_all_fields: 'Veuillez remplir tous les champs',
        different_establishments_required: 'Les établissements source et destination doivent être différents',
        quantity_greater_than_zero: 'La quantité doit être supérieure à 0',
        available: 'disponible',
        select_product: 'Sélectionner un produit',
        unknown_establishment: 'Établissement inconnu',
        select_product_first: 'Sélectionnez un produit',
        source_establishment: 'Établissement source',
        destination_establishment: 'Établissement destination',
        quantity_to_transfer: 'Quantité à transférer',
        available_stock: 'Stock disponible',
        max_quantity_available: 'Quantité maximale disponible',
        reason_optional: 'Motif (optionnel)',

        // ---------- AUTHENTIFICATION ----------
        fill_required_fields: 'Veuillez remplir tous les champs obligatoires',
        registration_success: 'Inscription réussie ! Redirection vers la connexion...',
        registration_error: 'Erreur lors de l\'inscription',
        registration_error_log: 'Erreur inscription',
        sending_data: 'Envoi des données',
        create_company_space: 'Créez votre espace entreprise',
        create_my_company_space: 'Créer mon espace entreprise',
        reset_password_title: 'Réinitialisation du mot de passe',
        reset_title: 'Réinitialisation',
        new_password_title: 'Nouveau mot de passe',
        reset_email_sent: 'Un email de réinitialisation a été envoyé',
        reset_link_hint: 'Un lien de réinitialisation vous sera envoyé par email',
        back_to_login: 'Retour à la connexion',
        email_required: 'Veuillez saisir votre email',
        error_request: 'Erreur lors de la demande',
        error_server_connection: 'Erreur de connexion au serveur',
        missing_token: 'Token manquant',
        invalid_token: 'Token invalide',
        invalid_or_expired_token: 'Token invalide ou expiré',
        invalid_or_expired_link: 'Lien invalide ou expiré',
        request_new_link: 'Demander un nouveau lien',
        password_reset_success: 'Mot de passe réinitialisé avec succès !',
        reset_error: 'Erreur lors de la réinitialisation',
        
        // ---------- PWA ----------
        install_app_title: 'Installer StockMedi',
        install_app_subtitle: 'Installez l\'application pour un accès rapide',
        install: 'Installer',
        pwa_accepted: 'Utilisateur a accepté l\'installation',
        pwa_declined: 'Utilisateur a refusé l\'installation',
        pharma_solution: 'Solution de gestion pharmaceutique',
        
        // ---------- COMMUN ----------
        cancel_btn: 'Annuler',
        confirm: 'Confirmer',
        back: 'Retour',
        search_btn: 'Rechercher',
        filter: 'Filtrer',
        all: 'Tous',
        yes: 'Oui',
        no: 'Non',
        read_only: 'Lecture seule',
        no_permission: 'Vous n\'avez pas la permission',
        contact_admin: 'Contactez votre administrateur',
        notes: 'Notes',
        update_available: 'Une nouvelle version est disponible !',
        update_now: 'Mettre à jour',
        
        // ---------- PIED DE PAGE ----------
        footer_description: 'Solution de gestion pharmaceutique multi-espaces pour pharmacies, cliniques et hôpitaux.',
        footer_quick_links: 'Liens rapides',
        footer_information: 'Informations',
        footer_about: 'À propos',
        footer_privacy: 'Confidentialité',
        footer_terms: "Conditions d'utilisation",
        footer_contact: 'Contact',
        footer_contact_title: 'Contact',
        footer_hours: 'Lundi - Vendredi: 8h - 18h',
        footer_copyright: 'Tous droits réservés.',
        footer_version: 'Version',
        footer_developed: 'Développé avec',
        footer_for_health: 'pour la santé',
        footer_rights: 'Tous droits réservés.',
        footer_developed_by: 'Développé par',

        // ---------- CONFIDENTIALITÉ ----------
        back_to_dashboard: 'Retour au tableau de bord',
        privacy_title: 'Charte de confidentialité',
        privacy_last_update: 'Dernière mise à jour',
        privacy_intro_title: 'Introduction',
        privacy_intro_text: 'StockMedi s\'engage à protéger vos données personnelles. Cette charte de confidentialité explique quelles informations nous collectons, comment nous les utilisons et comment vous pouvez les contrôler.',
        privacy_intro_text2: 'En utilisant StockMedi, vous acceptez les pratiques décrites dans ce document.',
        privacy_data_collected: 'Données collectées',
        privacy_data_collected_text: 'Nous collectons les informations suivantes :',
        privacy_account: 'Informations de compte',
        privacy_account_text: 'nom, prénom, email, téléphone',
        privacy_company: 'Informations d\'entreprise',
        privacy_company_text: 'nom, adresse, type d\'établissement',
        privacy_activity: 'Données d\'activité',
        privacy_activity_text: 'produits, ventes, employés, paramètres',
        privacy_payment: 'Données de paiement',
        privacy_payment_text: 'traitées par Stripe (nous ne stockons pas les données de carte)',
        privacy_data_usage: 'Utilisation des données',
        privacy_data_usage_text: 'Vos données sont utilisées pour :',
        privacy_usage_1: 'Gérer votre compte et votre abonnement',
        privacy_usage_2: 'Traiter vos ventes et votre stock',
        privacy_usage_3: 'Générer vos rapports',
        privacy_usage_4: 'Améliorer nos services',
        privacy_usage_5: 'Vous contacter concernant votre abonnement',
        privacy_data_sharing: 'Partage des données',
        privacy_data_sharing_text: 'Nous ne vendons jamais vos données à des tiers. Vos données peuvent être partagées avec :',
        privacy_sharing_stripe: 'pour les paiements (données de carte non stockées)',
        privacy_sharing_mongodb: 'pour l\'hébergement sécurisé des données',
        privacy_sharing_legal: 'si requis par la loi',
        privacy_security: 'Sécurité des données',
        privacy_security_text: 'Nous mettons en œuvre des mesures de sécurité techniques et organisationnelles :',
        privacy_security_1: 'Chiffrement des mots de passe (SHA256)',
        privacy_security_2: 'Authentification par token JWT',
        privacy_security_3: 'Connexion HTTPS',
        privacy_security_4: 'Accès restreint aux données',
        privacy_retention: 'Conservation des données',
        privacy_retention_text: 'Vos données sont conservées tant que votre compte est actif. En cas de suppression de compte, vos données sont anonymisées dans un délai de 30 jours, sauf obligation légale de conservation.',
        privacy_rights: 'Vos droits',
        privacy_rights_text: 'Conformément au RGPD, vous disposez des droits suivants :',
        privacy_rights_1: "Droit d'accès à vos données",
        privacy_rights_2: 'Droit de rectification',
        privacy_rights_3: "Droit à l'effacement",
        privacy_rights_4: 'Droit à la portabilité',
        privacy_rights_5: "Droit d'opposition",
        privacy_rights_contact: 'Pour exercer vos droits, contactez-nous à :',
        privacy_contact: 'Contact',
        privacy_contact_text: 'Pour toute question concernant cette charte de confidentialité, vous pouvez nous contacter :',
        privacy_changes: 'Modifications de la charte',
        privacy_changes_text: 'Nous pouvons modifier cette charte de confidentialité. Les modifications seront publiées sur cette page avec une date de mise à jour. Nous vous informerons des changements importants par email.',
        privacy_footer: 'Tous droits réservés.',
        privacy_version: 'Version',
        privacy_last_review: 'Dernière révision',
    },

    // ==================== ENGLISH ====================
    en: {
        // ---------- GENERAL ----------
        app_name: 'StockMedi',
        loading: 'Loading...',
        error: 'Error',
        success: 'Success',
        login: 'Login',
        register: 'Register',
        logout: 'Logout',
        email: 'Email',
        password: 'Password',
        confirm_password: 'Confirm password',
        first_name: 'First name',
        last_name: 'Last name',
        phone: 'Phone',
        send: 'Send',
        locale: 'en',
        
        // ---------- NAVIGATION ----------
        nav_dashboard: 'Dashboard',
        nav_products: 'Products',
        nav_sales: 'Sales',
        nav_reports: 'Reports',
        nav_employees: 'Employees',
        nav_settings: 'Settings',
        nav_subscription: 'Subscription',
        nav_quotes: 'Quotes',
        nav_admin: 'Admin',
        nav_logout: 'Logout',
        forgot_password: 'Forgot password?',
        no_account: "Don't have an account?",
        create_account: 'Create account',
        already_have_account: 'Already have an account?',
        close_menu: 'Close menu',
        open_menu: 'Open menu',
        menu: 'Menu',
        
        // ---------- DASHBOARD ----------
        dashboard_title: 'Dashboard',
        dashboard_welcome: 'Welcome to StockMedi. Here is an overview of your activity.',
        hello: 'Hello',
        daily_dashboard: 'here is your daily dashboard',
        sales_today: "Today's sales",
        sales_month: 'Monthly sales',
        transactions: 'transaction(s)',
        quick_actions: 'Quick actions',
        add_product: 'Add product',
        new_sale: 'New sale',
        export_report: 'Export report',
        top_products: 'Top selling products',
        quantity_sold: 'Quantity sold',
        revenue: 'Revenue',
        view_archives: 'View archives',
        archive_and_reset: 'Archive and reset',
        archive_and_reset_success: 'Dashboard archived and reset successfully',
        archive_confirm_message: 'This action will archive current dashboard data and reset counters. Archived data remains viewable. Confirm?',
        yes_archive: 'Yes, archive',
        product: 'Product',
        my_sales_today: 'My sales today',
        manage_products: 'Manage products',
        stock_entry: 'Stock entry',
        no_quick_actions: 'No quick actions available. Contact your administrator.',
        migrate_products_confirm: 'You have {{count}} product(s) not assigned to any establishment. Do you want to assign them to "{{name}}"?',
        
        // ---------- ARCHIVES ----------
        dashboard_archives: 'Dashboard Archives',
        archives_subtitle: 'View reset history',
        year: 'Year',
        month: 'Month',
        all_years: 'All years',
        all_months: 'All months',
        period: 'Period',
        archive_date: 'Archive date',
        type: 'Type',
        sales_period: 'Sales (period)',
        manual: 'Manual',
        auto: 'Auto',
        no_archives_found: 'No archives found',
        previous: 'Previous',
        next: 'Next',
        page: 'Page',
        delete_permanently: 'Delete permanently',
        confirm_delete_archive: 'Are you sure you want to permanently delete archive',
        action_irreversible: 'This action is irreversible.',
        yes_delete: 'Yes, delete',
        error_loading_archives: 'Error loading archives',
        archive_deleted_success: 'Archive permanently deleted',
        error_deleting_archive: 'Error deleting archive',
        
        // ---------- ALERTS ----------
        click_to_view: 'Click to view',
        alerts: 'Important alerts',
        out_of_stock: 'Out of stock',
        low_stock: 'Low stock',
        expiring_soon: 'Expiring soon',
        expired: 'Expired',
        out_of_stock_products: 'product(s) out of stock',
        low_stock_products: 'product(s) low stock',
        expiring_soon_products: 'product(s) expiring within 30 days',
        expired_products: 'product(s) expired',
        
        // ---------- PRODUCTS ----------
        products_title: 'Product Management',
        products_subtitle: 'Manage your medical products inventory',
        new_product: 'New product',
        search: 'Search',
        search_placeholder: 'Name, generic name, barcode...',
        category: 'Category',
        all_categories: 'All',
        stock_status: 'Stock status',
        all_status: 'All',
        reset: 'Reset',
        name: 'Name',
        category_col: 'Category',
        stock: 'Stock',
        purchase_price: 'Purchase price',
        selling_price: 'Selling price',
        margin: 'Margin',
        expiration: 'Expiration',
        actions: 'Actions',
        no_products: 'No products found',
        edit: 'Edit',
        delete: 'Delete',
        confirm_delete: 'Are you sure you want to archive',
        product_name: 'Product name',
        generic_name: 'Generic name',
        manufacturer: 'Manufacturer',
        batch_number: 'Batch number',
        barcode: 'Barcode',
        quantity: 'Quantity',
        unit: 'Unit',
        reorder_point: 'Reorder point',
        location: 'Location',
        manufacturing_date: 'Manufacturing date',
        expiration_date: 'Expiration date',
        description: 'Description',
        prescription_required: 'Prescription required',
        margin_info: 'Profit margin',
        sell_at_loss: 'SELLING AT A LOSS',
        margin_zero: 'ZERO MARGIN',
        margin_zero_confirm: 'Zero margin. Confirm?',
        add: 'Add',
        save: 'Save',
        product_created: 'Product created successfully',
        product_updated: 'Product updated successfully',
        product_deleted: 'Product archived successfully',
        product_name_required: 'Product name is required',
        purchase_price_required: 'Purchase price is required',
        selling_price_required: 'Selling price is required',
        expiration_date_required: 'Expiration date is required',
        purchase_price_zero: 'Purchase price cannot be zero',
        manufacturing_after_expiration: 'Manufacturing date cannot be after expiration date',
        expired_confirm: 'Expiration date has already passed. Do you want to continue?',
        no_products_search: 'No products match your search',
        in_stock: 'In stock',
        dci: 'INN',
        princeps: 'Princeps',
        generique: 'Generic',
        medication: 'Medication',
        medical_device: 'Medical Device',
        parapharmacy: 'Parapharmacy',
        food_supplement: 'Food Supplement',
        vitamin: 'Vitamin',
        medical_service: 'Medical Service',
        service_type: 'Service type',
        blood_pressure: 'Blood pressure',
        weight: 'Weight',
        height: 'Height',
        heart_rate: 'Heart rate',
        glycemia_test: 'Blood glucose test',
        vaccination: 'Vaccination',
        tablets: 'Tablets',
        capsules: 'Capsules',
        blisters: 'Blisters',
        ampoules: 'Ampoules',
        boxes: 'Boxes',
        box: 'Box(es)',
        bottle: 'Bottle',
        fabricant: 'Manufacturer',
        lot_number: 'Lot No.',
        lot: 'Lot',
        barcode_label: 'Barcode',
        location_label: 'Location',
        unit_label: 'Unit',
        alert_threshold: 'Alert threshold',
        purchase_price_label: 'Purchase price',
        selling_price_label: 'Selling price',
        manufacturing_date_label: 'Manufacturing date',
        expiration_date_label: 'Expiration date',
        description_label: 'Description',
        prescription_required_label: 'Prescription required',
        lower_than: 'lower than',
        profit: 'Profit',
        select_establishment: 'Please select an establishment',
        dci_required: 'INN is required',
        na: 'N/A',
        select: 'Select',
        consumable: 'Consumable',
        
        // ---------- SALES ----------
        sales_title: 'Point of Sale',
        sales_subtitle: 'Record your sales quickly',
        history: 'Sales history',
        back_to_pos: 'Back to point of sale',
        search_product: 'Search product',
        available_products: 'Available products',
        cart: 'Cart',
        empty_cart: 'Cart is empty',
        customer: 'Customer',
        client: 'Client',
        customer_name: 'Customer name',
        customer_phone: 'Phone',
        prescription_number: 'Prescription No.',
        subtotal: 'Subtotal',
        discount: 'Discount',
        tax: 'VAT (18%)',
        total: 'Total',
        payment_method: 'Payment method',
        cash: 'Cash',
        card: 'Card',
        mobile_money: 'Mobile Money',
        mixed: 'Mixed',
        validate: 'Validate sale',
        clear: 'Clear',
        confirm_sale: 'Confirm sale',
        confirm_message: 'Do you confirm this sale?',
        items: 'Items',
        payment: 'Payment',
        status: 'Status',
        validated: 'Validated',
        cancelled: 'Cancelled',
        prescription_required_error: 'This product requires a prescription.',
        stock_insufficient: 'Insufficient stock',
        max_available: 'Maximum available',
        sale_success: 'Sale recorded successfully!',
        search_hint: 'Enter at least 2 characters',
        customer_name_placeholder: 'Customer name (optional)',
        customer_phone_placeholder: 'Phone (optional)',
        prescription_placeholder: 'If applicable',
        sale_number: 'Sale No.',
        date: 'Date',
        no_sales: 'No sales recorded',
        receipt: 'Receipt',
        view_receipt: 'View receipt',
        print: 'Print',
        download: 'Download',
        share: 'Share',
        close: 'Close',
        thank_you: 'Thank you for your visit!',
        client_comptant: 'Cash customer',
        seller: 'Seller',
        enterprise_plan_promo: '💡 To manage multiple locations, upgrade to',
        search_placeholder_sales: 'Name, generic, barcode...',
        no_products_in_establishment: 'No products found in this establishment',
        no_permission_sales: 'You do not have permission to create sales',
        quantity_short: 'Qty',
        price_short: 'Price',
        total_short: 'Total',
        designation: 'Designation',
        unit_price_short: 'U.P.',
        created_on: 'Created on',
        by: 'by',
        not_provided: 'Not provided',
        view_sales: 'View sales',
        
        // ---------- QUOTES / PROFORMAS ----------
        quotes_title: 'Quotes / Proformas',
        quotes_subtitle: 'Manage your quotes and convert them to sales',
        new_quote: 'New quote',
        quote_details: 'Quote details',
        create_quote: 'Create a quote for your client',
        generate_quote: 'Generate quote',
        quote_number: 'Quote No.',
        quote_date: 'Date',
        quote_valid_until: 'Valid until',
        quote_validity: 'This quote is valid for 7 days',
        quote_thank_you: 'Thank you for your trust',
        quote_converted: 'This quote was converted to a sale on',
        quote_converted_on: 'This quote was converted to a sale on',
        convert_to_sale: 'Convert to sale',
        convert_confirm: 'Are you sure you want to convert this quote to a sale? Stock will be deducted.',
        convert: 'Convert',
        quote_converted_success: 'Quote converted to sale successfully!',
        quote_deleted_success: 'Quote deleted successfully',
        quote_delete_confirm: 'Are you sure you want to delete quote',
        delete_quote: 'Delete quote',
        cannot_convert: 'This quote cannot be converted to a sale',
        quote_status_draft: 'Draft',
        quote_status_sent: 'Sent',
        quote_status_converted: 'Converted',
        quote_status_expired: 'Expired',
        quote_status_cancelled: 'Cancelled',
        all_quotes: 'All quotes',
        no_quotes: 'No quotes found',
        quote_items: 'Items',
        quote_client: 'Client',
        quote_notes: 'Notes',
        quote: 'Quote',
        view: 'View',
        error_loading_quote: 'Error loading quote',
        error_loading_quotes: 'Error loading quotes',
        error_creating_quote: 'Error creating quote',
        error_converting: 'Error converting',
        quote_not_found: 'Quote not found',
        notes_placeholder: 'Notes...',
        
        // ---------- REPORTS ----------
        reports_title: 'Reports & Exports',
        reports_subtitle: 'Export your data to PDF or Excel',
        inventory: 'Inventory Report',
        inventory_desc: 'Export complete product list with stock, prices and expiration dates.',
        sales_report: 'Sales Report',
        sales_desc: 'Export sales history with transaction details.',
        download_pdf: 'Download PDF',
        download_excel: 'Download Excel',
        start_date: 'Start date',
        end_date: 'End date',
        leave_empty: 'Leave empty to export all sales',
        info_title: 'Export Information',
        info_pdf: 'Print-optimized format',
        info_excel: 'Editable format with summary sheet and detailed data',
        info_filter: 'Sales reports can be filtered by period',
        info_currency: 'All amounts are displayed in',
        download_success: 'File downloaded successfully',
        download_error: 'Error downloading file',
        reports_filtered_by_establishment: 'Reports will be generated for the selected establishment.',
        filterable_by_establishment: 'Filterable by establishment',
        reports_filterable_by_establishment: 'Reports filterable by establishment',

        // ---------- EMPLOYEES ----------
        employees_title: 'Employee Management',
        employees_subtitle: 'Manage your employees and their permissions',
        add_employee: 'Add employee',
        no_employees: 'No employees. Click "Add employee" to get started.',
        employee: 'Employee',
        contact: 'Contact',
        discipline: 'Discipline',
        permissions: 'Permissions',
        active: 'Active',
        inactive: 'Inactive',
        first_name_placeholder: 'Viviane Boma',
        last_name_placeholder: 'Onivogui',
        email_placeholder: 'vivianeboma@email.com',
        phone_placeholder: '620000000',
        discipline_label: 'Discipline / Specialty',
        pharmacist: 'Pharmacist',
        doctor: 'Doctor',
        nurse: 'Nurse',
        assistant: 'Assistant',
        accountant: 'Accountant',
        other: 'Other',
        permissions_label: 'Permissions',
        manage_stock: 'Stock management',
        make_sales: 'Sales',
        view_reports: 'Reports',
        view_dashboard: 'View dashboard',
        view_products: 'View products',
        cancel_sales: 'Cancel sales',
        manage_employees: 'Manage employees',
        manage_establishments: 'Manage establishments',
        manage_settings: 'Settings',
        password_mismatch: 'Passwords do not match',
        password_too_short: 'Password must be at least 6 characters',
        employee_added: 'Employee added successfully',
        employee_updated: 'Employee updated successfully',
        employee_deleted: 'Employee deleted successfully',
        email_cannot_change: 'Email cannot be changed',
        activate: 'Activate',
        deactivate: 'Deactivate',
        employee_limit_reached: 'Employee limit reached. Upgrade to a higher plan.',
        establishments: 'Establishments',
        all_establishments: 'All',
        establishments_access: 'Establishment access',
        establishments_hint: 'If no establishment is selected, the employee will have access to all.',
        
        // ---------- SETTINGS ----------
        settings_title: 'Settings',
        settings_subtitle: 'Configure your company and user account',
        company: 'Company',
        profile: 'My profile',
        company_info: 'Company information',
        company_name: 'Company name',
        company_name_placeholder: 'Central Pharmacy',
        company_phone: 'Company phone',
        company_phone_placeholder: '620000000',
        company_email: 'Email',
        address: 'Address',
        city: 'City',
        city_placeholder: 'Conakry',
        street: 'Street',
        postal_code: 'Postal code',
        country: 'Country',
        preferences: 'Preferences',
        currency: 'Currency',
        language: 'Language',
        tax_rate: 'Tax rate (%)',
        invoice_prefix: 'Invoice prefix',
        expiration_alerts: 'Expiration alerts (days)',
        batch_tracking: 'Batch tracking',
        prescription_default: 'Prescription required by default',
        personal_info: 'Personal information',
        role: 'Role',
        update_profile: 'Update profile',
        change_password: 'Change password',
        current_password: 'Current password',
        new_password: 'New password',
        save_success: 'Settings saved successfully',
        profile_updated: 'Profile updated successfully',
        password_changed: 'Password changed successfully',
        current_password_required: 'Please enter your current password',
        new_password_required: 'Please enter a new password',
        owner: 'Owner',
        super_admin: 'Super Admin',
        role_employee: 'Employee',
        expiration_hint: 'Alert X days before expiration',
        logo_url: 'Logo (URL)',
        logo_url_placeholder: 'https://...',

        // ---------- REGISTRATION & TERMS ----------
        accept_terms: 'I accept the',
        terms_of_use: 'terms of use',
        must_accept_terms: 'You must accept the terms of use',

        // ---------- ACCOUNT DELETION (GDPR) ----------
        delete_account: 'Delete my account',
        delete_account_warning: 'Account deletion is permanent and irreversible.',
        delete_account_confirm: 'I understand this action is permanent',
        delete_account_password: 'Enter your password to confirm',
        delete_account_success: 'Your account has been successfully deleted',
        delete_account_error: 'Incorrect password',
        danger_zone: 'Danger zone',
        inactivity_deletion_subject: 'Your StockMedi account will be deleted soon',
        inactivity_deletion_body: 'Your account has been inactive for {months} months. It will be deleted in {days} days.',
        deletion_pending: 'A deletion request is in progress.',
        deletion_scheduled: 'Your account will be deleted on',
        cancel_deletion: 'Cancel request',
        request_deletion: 'Request account deletion',
        confirm_deletion: 'Confirm',
        deletion_delay_warning: 'Your account will be deleted in 7 days. You can cancel before this delay.',
        
        // ---------- SUBSCRIPTION ----------
        subscription_title: 'Subscription',
        subscription_subtitle: 'Manage your subscription and choose the plan that suits your needs',
        current_subscription: 'Your current subscription',
        valid_until: 'Valid until',
        days_remaining: 'Days remaining',
        auto_renew: 'Auto-renewal',
        cancel: 'Cancel',
        choose_plan: 'Choose your plan',
        free: 'Free',
        trial: 'Start trial',
        subscribe: 'Subscribe',
        current_plan: 'Current plan',
        products_max: 'max products',
        employees_max: 'max employees',
        cancel_confirm: 'Cancel your subscription? You can continue until the end of the period.',
        payment_error: 'Error initializing payment',
        days: 'days',
        redirecting: 'Redirecting...',
        stock_basic: 'Basic stock management',
        stock_advanced: 'Advanced stock management',
        sales_basic: 'Basic sales',
        sales_advanced: 'Advanced sales + cart',
        reports_basic: 'Basic reports',
        reports_advanced: 'Advanced reports + charts',
        pdf_exports: 'PDF/Excel export',
        employees_management: 'Employee management',
        advanced_stats: 'Advanced statistics',
        multiple_locations: 'Multiple locations',
        api_access: 'API Access',
        priority_support: 'Priority support',
        local_payment_title: 'Local Payment Request',
        full_name: 'Full Name',
        full_name_placeholder: 'Dr. Viviane Boma',
        preferred_contact: 'Preferred Contact Method',
        additional_message: 'Additional Message (optional)',
        additional_message_placeholder: 'Additional information...',
        payment_info_title: 'How Local Payment Works',
        payment_info_description: 'After your request is validated, you will receive instructions to complete the payment via Mobile Money. Your subscription will only be activated after payment is received.',
        mobile_money_numbers: 'Mobile Money Numbers',
        submit_request: 'Submit Request',
        payment_request_success: 'Your request has been sent successfully! You will receive a confirmation email.',
        error_submitting: 'Error submitting request',
        request_received: 'Request Received!',
        request_received_description: 'Thank you. Your request has been recorded. You will receive a confirmation email shortly.',
        local_payment_option: 'Local Payment Option',
        local_payment_description: 'Don\'t have a card to pay via Stripe? Pay with Mobile Money.',
        pay_by_mobile_money: 'Pay via Mobile Money',
        
        // ---------- ESTABLISHMENTS ----------
        establishments_title: 'Establishments',
        establishments_subtitle: 'Manage your pharmacies, clinics and points of sale',
        new_establishment: 'New establishment',
        transfer_stock: 'Transfer stock',
        establishment_name: 'Establishment name',
        establishment_type: 'Establishment type',
        pharmacy: 'Pharmacy',
        clinic: 'Clinic',
        hospital: 'Hospital',
        lab: 'Laboratory',
        warehouse: 'Warehouse',
        establishment_created: 'Establishment created successfully',
        establishment_updated: 'Establishment updated successfully',
        establishment_deleted: 'Establishment deleted successfully',
        establishment: 'Establishment',
        loading_establishments: 'Loading establishments...',
        no_establishments_create_one: 'No establishments. Create one in settings.',
        establishment_count: 'establishment(s)',
        establishment_name_placeholder: 'Central Pharmacy',
        street_placeholder: 'Kaloum, Boulevard Louise Lansana Béavogui',
        products_migrated_success: 'Products migrated successfully',
        error_migrating_products: 'Error migrating products',
        restock_transfer_etc: 'Restock, transfer, etc.',

        // ---------- STOCK TRANSFER ----------
        transfer: 'Transfer',
        transfer_success: 'Transfer completed successfully',
        error_transfer: 'Transfer error',
        error_loading_data: 'Error loading data',
        fill_all_fields: 'Please fill in all fields',
        different_establishments_required: 'Source and destination establishments must be different',
        quantity_greater_than_zero: 'Quantity must be greater than 0',
        available: 'available',
        select_product: 'Select a product',
        unknown_establishment: 'Unknown establishment',
        select_product_first: 'Select a product first',
        source_establishment: 'Source establishment',
        destination_establishment: 'Destination establishment',
        quantity_to_transfer: 'Quantity to transfer',
        available_stock: 'Available stock',
        max_quantity_available: 'Maximum quantity available',
        reason_optional: 'Reason (optional)',
        
        // ---------- AUTHENTICATION ----------
        fill_required_fields: 'Please fill in all required fields',
        registration_success: 'Registration successful! Redirecting to login...',
        registration_error: 'Registration error',
        registration_error_log: 'Registration error',
        sending_data: 'Sending data',
        create_company_space: 'Create your company space',
        create_my_company_space: 'Create my company space',
        reset_password_title: 'Password reset',
        reset_title: 'Reset',
        new_password_title: 'New password',
        reset_email_sent: 'A reset email has been sent',
        reset_link_hint: 'A reset link will be sent to your email',
        back_to_login: 'Back to login',
        email_required: 'Please enter your email',
        error_request: 'Request error',
        error_server_connection: 'Server connection error',
        missing_token: 'Missing token',
        invalid_token: 'Invalid token',
        invalid_or_expired_token: 'Invalid or expired token',
        invalid_or_expired_link: 'Invalid or expired link',
        request_new_link: 'Request a new link',
        password_reset_success: 'Password reset successfully!',
        reset_error: 'Reset error',
        
        // ---------- PWA ----------
        install_app_title: 'Install StockMedi',
        install_app_subtitle: 'Install the app for quick access',
        install: 'Install',
        pwa_accepted: 'User accepted installation',
        pwa_declined: 'User declined installation',
        pharma_solution: 'Pharmaceutical Management Solution',
        
        // ---------- COMMON ----------
        cancel_btn: 'Cancel',
        confirm: 'Confirm',
        back: 'Back',
        search_btn: 'Search',
        filter: 'Filter',
        all: 'All',
        yes: 'Yes',
        no: 'No',
        read_only: 'Read only',
        no_permission: 'You do not have permission',
        contact_admin: 'Contact your administrator',
        notes: 'Notes',
        update_available: 'A new version is available!',
        update_now: 'Update now',

        // ---------- FOOTER ----------
        footer_description: 'Multi-space pharmaceutical management solution for pharmacies, clinics and hospitals.',
        footer_quick_links: 'Quick links',
        footer_information: 'Information',
        footer_about: 'About',
        footer_privacy: 'Privacy',
        footer_terms: 'Terms of use',
        footer_contact: 'Contact',
        footer_contact_title: 'Contact',
        footer_hours: 'Monday - Friday: 8am - 6pm',
        footer_copyright: 'All rights reserved.',
        footer_version: 'Version',
        footer_developed: 'Developed with',
        footer_for_health: 'for health',
        footer_rights: 'All rights reserved.',
        footer_developed_by: 'Developed by',

        // ---------- PRIVAVACY ----------
        back_to_dashboard: 'Back to dashboard',
        privacy_title: 'Privacy Policy',
        privacy_last_update: 'Last updated',
        privacy_intro_title: 'Introduction',
        privacy_intro_text: 'StockMedi is committed to protecting your personal data. This privacy policy explains what information we collect, how we use it, and how you can control it.',
        privacy_intro_text2: 'By using StockMedi, you agree to the practices described in this document.',
        privacy_data_collected: 'Data collected',
        privacy_data_collected_text: 'We collect the following information:',
        privacy_account: 'Account information',
        privacy_account_text: 'name, first name, email, phone',
        privacy_company: 'Company information',
        privacy_company_text: 'name, address, establishment type',
        privacy_activity: 'Activity data',
        privacy_activity_text: 'products, sales, employees, settings',
        privacy_payment: 'Payment data',
        privacy_payment_text: 'processed by Stripe (we do not store card data)',
        privacy_data_usage: 'Data usage',
        privacy_data_usage_text: 'Your data is used to:',
        privacy_usage_1: 'Manage your account and subscription',
        privacy_usage_2: 'Process your sales and inventory',
        privacy_usage_3: 'Generate your reports',
        privacy_usage_4: 'Improve our services',
        privacy_usage_5: 'Contact you regarding your subscription',
        privacy_data_sharing: 'Data sharing',
        privacy_data_sharing_text: 'We never sell your data to third parties. Your data may be shared with:',
        privacy_sharing_stripe: 'for payments (card data not stored)',
        privacy_sharing_mongodb: 'for secure data hosting',
        privacy_sharing_legal: 'if required by law',
        privacy_security: 'Data security',
        privacy_security_text: 'We implement technical and organizational security measures:',
        privacy_security_1: 'Password encryption (SHA256)',
        privacy_security_2: 'JWT token authentication',
        privacy_security_3: 'HTTPS connection',
        privacy_security_4: 'Restricted data access',
        privacy_retention: 'Data retention',
        privacy_retention_text: 'Your data is kept as long as your account is active. In case of account deletion, your data is anonymized within 30 days, unless required by law.',
        privacy_rights: 'Your rights',
        privacy_rights_text: 'Under GDPR, you have the following rights:',
        privacy_rights_1: 'Right of access to your data',
        privacy_rights_2: 'Right of rectification',
        privacy_rights_3: 'Right to erasure',
        privacy_rights_4: 'Right to data portability',
        privacy_rights_5: 'Right to object',
        privacy_rights_contact: 'To exercise your rights, contact us at:',
        privacy_contact: 'Contact',
        privacy_contact_text: 'For any questions regarding this privacy policy, you can contact us:',
        privacy_changes: 'Policy changes',
        privacy_changes_text: 'We may update this privacy policy. Changes will be posted on this page with an updated date. We will notify you of material changes by email.',
        privacy_footer: 'All rights reserved.',
        privacy_version: 'Version',
        privacy_last_review: 'Last reviewed',
    }
};

// ============================================================
// CONTEXTE ET PROVIDER
// ============================================================

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        const saved = localStorage.getItem('language');
        return saved || 'fr';
    });

    const t = (key) => {
        return translations[language]?.[key] || key;
    };

    const changeLanguage = (lang) => {
        setLanguage(lang);
        localStorage.setItem('language', lang);
    };

    return (
        <LanguageContext.Provider value={{ language, t, changeLanguage }}>
            {children}
        </LanguageContext.Provider>
    );
};