import React, { createContext, useState, useContext } from 'react';

// Traductions complètes
const translations = {
    fr: {
        // ========== GÉNÉRAL ==========
        app_name: 'StockMedi',
        loading: 'Chargement...',
        error: 'Erreur',
        success: 'Succès',
        
        // ========== NAVIGATION ==========
        nav_dashboard: 'Tableau de bord',
        nav_products: 'Produits',
        nav_sales: 'Ventes',
        nav_reports: 'Rapports',
        nav_employees: 'Employés',
        nav_settings: 'Paramètres',
        nav_subscription: 'Abonnement',
        nav_admin: 'Admin',
        nav_logout: 'Déconnexion',
        
        // ========== DASHBOARD ==========
        dashboard_title: 'Tableau de bord',
        dashboard_welcome: 'Bienvenue sur StockMedi. Voici un aperçu de votre activité.',
        sales_today: 'Ventes du jour',
        sales_month: 'Ventes du mois',
        transactions: 'transaction(s)',
        quick_actions: 'Actions rapides',
        add_product: 'Ajouter un produit',
        new_sale: 'Nouvelle vente',
        export_report: 'Exporter rapport',
        top_products: 'Top des produits les plus vendus',
        quantity_sold: 'Quantité vendue',
        revenue: 'Chiffre d\'affaires',
        
        // ========== ALERTES ==========
        click_to_view: 'Cliquez pour voir',
        alerts: 'Alertes importantes',
        out_of_stock: 'Rupture',
        low_stock: 'Stock faible',
        expiring_soon: 'Expire bientôt',
        expired: 'Expiré',
        
        // ========== PRODUITS ==========
        products_title: 'Gestion des produits',
        products_subtitle: 'Gérez votre stock de produits médicaux',
        new_product: 'Nouveau produit',
        search: 'Recherche',
        search_placeholder: 'Nom, générique, code-barres...',
        category: 'Catégorie',
        all_categories: 'Toutes',
        stock_status: 'Statut stock',
        all_status: 'Tous',
        reset: 'Réinitialiser',
        name: 'Nom',
        category_col: 'Catégorie',
        stock: 'Stock',
        purchase_price: "Prix d'achat",
        selling_price: 'Prix de vente',
        margin: 'Marge',
        expiration: 'Expiration',
        actions: 'Actions',
        no_products: 'Aucun produit trouvé',
        edit: 'Modifier',
        delete: 'Supprimer',
        confirm_delete: 'Voulez-vous vraiment archiver le produit',
        product_name: 'Nom du produit',
        generic_name: 'Nom générique',
        manufacturer: 'Fabricant',
        batch_number: 'Numéro de lot',
        barcode: 'Code-barres',
        quantity: 'Quantité',
        unit: 'Unité',
        reorder_point: "Seuil d'alerte",
        location: 'Emplacement',
        manufacturing_date: 'Date de fabrication',
        expiration_date: "Date d'expiration",
        description: 'Description',
        prescription_required: 'Ordonnance requise',
        margin_info: 'Marge bénéficiaire',
        sell_at_loss: 'VENTE À PERTE',
        margin_zero: 'MARGE NULLE',
        add: 'Ajouter',
        save: 'Enregistrer',
        
        // ========== VENTES ==========
        sales_title: 'Point de vente',
        sales_subtitle: 'Enregistrez vos ventes rapidement',
        history: 'Historique des ventes',
        back_to_pos: 'Retour au point de vente',
        search_product: 'Rechercher un produit',
        available_products: 'Produits disponibles',
        cart: 'Panier',
        empty_cart: 'Aucun produit dans le panier',
        customer: 'Client',
        customer_name: 'Nom du client (optionnel)',
        customer_phone: 'Téléphone (optionnel)',
        prescription_number: "Numéro d'ordonnance",
        subtotal: 'Sous-total',
        discount: 'Remise',
        tax: 'TVA (18%)',
        total: 'Total',
        payment_method: 'Mode de paiement',
        cash: 'Espèces',
        card: 'Carte bancaire',
        mobile_money: 'Mobile Money',
        mixed: 'Mixte',
        validate: 'Valider la vente',
        clear: 'Vider',
        confirm_sale: 'Confirmer la vente',
        confirm_message: 'Confirmez-vous cette vente ?',
        items: 'Articles',
        payment: 'Paiement',
        status: 'Statut',
        validated: 'Validée',
        cancelled: 'Annulée',
        prescription_required_error: 'Ce produit nécessite une ordonnance. Veuillez saisir le numéro d\'ordonnance.',
        stock_insufficient: 'Stock insuffisant',
        max_available: 'Maximum disponible',
        sale_success: 'Vente enregistrée avec succès !',
        search_hint: 'Saisissez au moins 2 caractères',
        customer_name_placeholder: 'Nom du client (optionnel)',
        customer_phone_placeholder: 'Téléphone (optionnel)',
        prescription_placeholder: 'Si applicable',
        sale_number: 'N° vente',
        date: 'Date',
        no_sales: 'Aucune vente enregistrée',
        in_stock: 'En stock',
        
        // ========== RAPPORTS ==========
        reports_title: 'Rapports et exportations',
        reports_subtitle: 'Exportez vos données en PDF ou Excel',
        inventory: "Rapport d'inventaire",
        inventory_desc: "Exportez la liste complète de vos produits avec les stocks, prix et dates d'expiration.",
        sales_report: 'Rapport des ventes',
        sales_desc: "Exportez l'historique de vos ventes avec détails par transaction.",
        download_pdf: 'Télécharger PDF',
        download_excel: 'Télécharger Excel',
        start_date: 'Date début',
        end_date: 'Date fin',
        leave_empty: 'Laissez vide pour exporter toutes les ventes',
        info_title: 'Informations sur les exports',
        info_pdf: 'Format optimisé pour l\'impression et l\'archivage',
        info_excel: 'Format modifiable avec feuille de résumé et données détaillées',
        info_filter: 'Les rapports de ventes peuvent être filtrés par période',
        info_currency: 'Tous les montants sont affichés en Francs Guinéens (GNF)',
        download_success: 'Fichier téléchargé avec succès',
        download_error: 'Erreur lors du téléchargement',
        
        // ========== EMPLOYÉS ==========
        employees_title: 'Gestion des employés',
        employees_subtitle: 'Gérez les comptes de vos employés et leurs permissions',
        add_employee: 'Ajouter un employé',
        no_employees: 'Aucun employé. Cliquez sur "Ajouter un employé" pour commencer.',
        employee: 'Employé',
        contact: 'Contact',
        discipline: 'Discipline',
        permissions: 'Permissions',
        active: 'Actif',
        inactive: 'Inactif',
        first_name: 'Prénom',
        last_name: 'Nom',
        email: 'Email',
        password: 'Mot de passe',
        confirm_password: 'Confirmer',
        phone: 'Téléphone',
        discipline_label: 'Discipline / Spécialité',
        pharmacist: 'Pharmacien',
        doctor: 'Médecin',
        nurse: 'Infirmier',
        assistant: 'Assistant',
        accountant: 'Comptable',
        other: 'Autre',
        permissions_label: 'Permissions',
        manage_stock: 'Gestion stock',
        make_sales: 'Ventes',
        view_reports: 'Rapports',
        manage_users: 'Gestion utilisateurs',
        manage_settings: 'Paramètres',
        password_mismatch: 'Les mots de passe ne correspondent pas',
        password_too_short: 'Le mot de passe doit contenir au moins 6 caractères',
        employee_added: 'Employé ajouté avec succès',
        employee_updated: 'Employé modifié avec succès',
        employee_deleted: 'Employé supprimé avec succès',
        email_cannot_change: "L'email ne peut pas être modifié",
        activate: 'Activer',
        deactivate: 'Désactiver',
        
        // ========== PARAMÈTRES ==========
        settings_title: 'Paramètres',
        settings_subtitle: 'Configurez votre entreprise et votre compte utilisateur',
        company: 'Entreprise',
        profile: 'Mon profil',
        company_info: "Informations de l'entreprise",
        company_name: "Nom de l'entreprise",
        company_phone: 'Téléphone',
        company_email: 'Email',
        address: 'Adresse',
        city: 'Ville',
        postal_code: 'Code postal',
        country: 'Pays',
        preferences: 'Préférences',
        currency: 'Devise',
        language: 'Langue',
        tax_rate: 'Taux de TVA (%)',
        invoice_prefix: 'Préfixe facture',
        expiration_alerts: 'Alertes expiration (jours)',
        batch_tracking: 'Suivi des lots',
        prescription_default: 'Ordonnance obligatoire par défaut',
        personal_info: 'Informations personnelles',
        role: 'Rôle',
        update_profile: 'Mettre à jour le profil',
        change_password: 'Changer le mot de passe',
        current_password: 'Mot de passe actuel',
        new_password: 'Nouveau mot de passe',
        save_success: 'Paramètres enregistrés avec succès',
        profile_updated: 'Profil mis à jour avec succès',
        password_changed: 'Mot de passe modifié avec succès',
        current_password_required: 'Veuillez saisir votre mot de passe actuel',
        new_password_required: 'Veuillez saisir un nouveau mot de passe',
        owner: 'Propriétaire',
        super_admin: 'Super Admin',
        role_employee: 'Employé',
        expiration_hint: 'Alerte X jours avant expiration',
        
        // ========== ABONNEMENT ==========
        subscription_title: 'Abonnement',
        subscription_subtitle: 'Gérez votre abonnement et choisissez le plan adapté à vos besoins',
        current_subscription: 'Votre abonnement actuel',
        valid_until: 'Valable jusqu\'au',
        days_remaining: 'Jours restants',
        auto_renew: 'Renouvellement automatique',
        cancel: 'Annuler',
        choose_plan: 'Choisissez votre plan',
        free: 'Gratuit',
        trial: 'Commencer l\'essai',
        subscribe: 'Souscrire',
        current_plan: 'Plan actuel',
        products_max: 'produits max',
        employees_max: 'employés max',
        cancel_confirm: 'Annuler votre abonnement ? Vous pourrez continuer jusqu\'à la fin de la période.',
        payment_error: 'Erreur lors de l\'initialisation du paiement',
        days: 'jours',
        redirecting: 'Redirection...',
        stock_basic: 'Gestion de stock basique',
        stock_advanced: 'Gestion de stock avancée',
        sales_basic: 'Ventes basiques',
        sales_advanced: 'Ventes avancées + panier',
        reports_basic: 'Rapports basiques',
        reports_advanced: 'Rapports avancés + graphiques',
        pdf_exports: 'Export PDF/Excel',
        employees_management: 'Gestion des employés',
        advanced_stats: 'Statistiques avancées',
        multiple_locations: 'Multi-emplacements',
        api_access: 'API Access',
        priority_support: 'Support prioritaire',
        
        // ========== COMMUN ==========
        cancel_btn: 'Annuler',
        confirm: 'Confirmer',
        close: 'Fermer',
        back: 'Retour',
        search_btn: 'Rechercher',
        filter: 'Filtrer',
        all: 'Tous',
        yes: 'Oui',
        no: 'Non',

        // ========== PIED DE PAGE ==========
        footer_description: 'Solution de gestion pharmaceutique multi-espaces pour pharmacies, cliniques et hôpitaux.',
        footer_quick_links: 'Liens rapides',
        footer_information: 'Informations',
        footer_about: 'À propos',
        footer_privacy: 'Confidentialité',
        footer_terms: "Conditions d'utilisation",
        footer_contact: 'Contact',
        footer_contact_title: 'Contact',
        footer_hours: 'Lundi - Vendredi: 8h - 18h',
        footer_copyright: 'Tous droits réservés.',
        footer_version: 'Version',
        footer_developed: 'Développé avec',
        footer_for_health: 'pour la santé',

        // ========== CONFIDENTIALITE ==========
        back_to_dashboard: 'Retour au tableau de bord',
        privacy_title: 'Charte de confidentialité',
        privacy_last_update: 'Dernière mise à jour',
        privacy_intro_title: 'Introduction',
        privacy_intro_text: 'StockMedi s\'engage à protéger vos données personnelles. Cette charte de confidentialité explique quelles informations nous collectons, comment nous les utilisons et comment vous pouvez les contrôler.',
        privacy_intro_text2: 'En utilisant StockMedi, vous acceptez les pratiques décrites dans ce document.',
        privacy_data_collected: 'Données collectées',
        privacy_data_collected_text: 'Nous collectons les informations suivantes :',
        privacy_account: 'Informations de compte',
        privacy_account_text: 'nom, prénom, email, téléphone',
        privacy_company: 'Informations d\'entreprise',
        privacy_company_text: 'nom, adresse, type d\'établissement',
        privacy_activity: 'Données d\'activité',
        privacy_activity_text: 'produits, ventes, employés, paramètres',
        privacy_payment: 'Données de paiement',
        privacy_payment_text: 'traitées par Stripe (nous ne stockons pas les données de carte)',
        privacy_data_usage: 'Utilisation des données',
        privacy_data_usage_text: 'Vos données sont utilisées pour :',
        privacy_usage_1: 'Gérer votre compte et votre abonnement',
        privacy_usage_2: 'Traiter vos ventes et votre stock',
        privacy_usage_3: 'Générer vos rapports',
        privacy_usage_4: 'Améliorer nos services',
        privacy_usage_5: 'Vous contacter concernant votre abonnement',
        privacy_data_sharing: 'Partage des données',
        privacy_data_sharing_text: 'Nous ne vendons jamais vos données à des tiers. Vos données peuvent être partagées avec :',
        privacy_sharing_stripe: 'pour les paiements (données de carte non stockées)',
        privacy_sharing_mongodb: 'pour l\'hébergement sécurisé des données',
        privacy_sharing_legal: 'si requis par la loi',
        privacy_security: 'Sécurité des données',
        privacy_security_text: 'Nous mettons en œuvre des mesures de sécurité techniques et organisationnelles :',
        privacy_security_1: 'Chiffrement des mots de passe (SHA256)',
        privacy_security_2: 'Authentification par token JWT',
        privacy_security_3: 'Connexion HTTPS',
        privacy_security_4: 'Accès restreint aux données',
        privacy_retention: 'Conservation des données',
        privacy_retention_text: 'Vos données sont conservées tant que votre compte est actif. En cas de suppression de compte, vos données sont anonymisées dans un délai de 30 jours, sauf obligation légale de conservation.',
        privacy_rights: 'Vos droits',
        privacy_rights_text: 'Conformément au RGPD, vous disposez des droits suivants :',
        privacy_rights_1: "Droit d'accès à vos données",
        privacy_rights_2: 'Droit de rectification',
        privacy_rights_3: "Droit à l'effacement",
        privacy_rights_4: 'Droit à la portabilité',
        privacy_rights_5: "Droit d'opposition",
        privacy_rights_contact: 'Pour exercer vos droits, contactez-nous à :',
        privacy_contact: 'Contact',
        privacy_contact_text: 'Pour toute question concernant cette charte de confidentialité, vous pouvez nous contacter :',
        privacy_changes: 'Modifications de la charte',
        privacy_changes_text: 'Nous pouvons modifier cette charte de confidentialité. Les modifications seront publiées sur cette page avec une date de mise à jour. Nous vous informerons des changements importants par email.',
        privacy_footer: 'Tous droits réservés.',
        privacy_version: 'Version',
        privacy_last_review: 'Dernière révision',
    },
    en: {
        // ========== GENERAL ==========
        app_name: 'StockMedi',
        loading: 'Loading...',
        error: 'Error',
        success: 'Success',
        
        // ========== NAVIGATION ==========
        nav_dashboard: 'Dashboard',
        nav_products: 'Products',
        nav_sales: 'Sales',
        nav_reports: 'Reports',
        nav_employees: 'Employees',
        nav_settings: 'Settings',
        nav_subscription: 'Subscription',
        nav_admin: 'Admin',
        nav_logout: 'Logout',
        
        // ========== DASHBOARD ==========
        dashboard_title: 'Dashboard',
        dashboard_welcome: 'Welcome to StockMedi. Here is an overview of your activity.',
        sales_today: "Today's sales",
        sales_month: 'Monthly sales',
        transactions: 'transaction(s)',
        quick_actions: 'Quick actions',
        add_product: 'Add product',
        new_sale: 'New sale',
        export_report: 'Export report',
        top_products: 'Top selling products',
        quantity_sold: 'Quantity sold',
        revenue: 'Revenue',
        
        // ========== ALERTS ==========
        click_to_view: 'Click to view',
        alerts: 'Important alerts',
        out_of_stock: 'Out of stock',
        low_stock: 'Low stock',
        expiring_soon: 'Expiring soon',
        expired: 'Expired',
        
        // ========== PRODUCTS ==========
        products_title: 'Product Management',
        products_subtitle: 'Manage your medical products inventory',
        new_product: 'New product',
        search: 'Search',
        search_placeholder: 'Name, generic name, barcode...',
        category: 'Category',
        all_categories: 'All',
        stock_status: 'Stock status',
        all_status: 'All',
        reset: 'Reset',
        name: 'Name',
        category_col: 'Category',
        stock: 'Stock',
        purchase_price: 'Purchase price',
        selling_price: 'Selling price',
        margin: 'Margin',
        expiration: 'Expiration',
        actions: 'Actions',
        no_products: 'No products found',
        edit: 'Edit',
        delete: 'Delete',
        confirm_delete: 'Are you sure you want to archive',
        product_name: 'Product name',
        generic_name: 'Generic name',
        manufacturer: 'Manufacturer',
        batch_number: 'Batch number',
        barcode: 'Barcode',
        quantity: 'Quantity',
        unit: 'Unit',
        reorder_point: 'Reorder point',
        location: 'Location',
        manufacturing_date: 'Manufacturing date',
        expiration_date: 'Expiration date',
        description: 'Description',
        prescription_required: 'Prescription required',
        margin_info: 'Profit margin',
        sell_at_loss: 'SELLING AT A LOSS',
        margin_zero: 'ZERO MARGIN',
        add: 'Add',
        save: 'Save',
        
        // ========== SALES ==========
        sales_title: 'Point of Sale',
        sales_subtitle: 'Record your sales quickly',
        history: 'Sales history',
        back_to_pos: 'Back to point of sale',
        search_product: 'Search product',
        available_products: 'Available products',
        cart: 'Cart',
        empty_cart: 'No products in cart',
        customer: 'Customer',
        customer_name: 'Customer name (optional)',
        customer_phone: 'Phone (optional)',
        prescription_number: 'Prescription number',
        subtotal: 'Subtotal',
        discount: 'Discount',
        tax: 'VAT (18%)',
        total: 'Total',
        payment_method: 'Payment method',
        cash: 'Cash',
        card: 'Card',
        mobile_money: 'Mobile Money',
        mixed: 'Mixed',
        validate: 'Validate sale',
        clear: 'Clear',
        confirm_sale: 'Confirm sale',
        confirm_message: 'Do you confirm this sale?',
        items: 'Items',
        payment: 'Payment',
        status: 'Status',
        validated: 'Validated',
        cancelled: 'Cancelled',
        prescription_required_error: 'This product requires a prescription. Please enter the prescription number.',
        stock_insufficient: 'Insufficient stock',
        max_available: 'Maximum available',
        sale_success: 'Sale recorded successfully!',
        search_hint: 'Enter at least 2 characters',
        customer_name_placeholder: 'Customer name (optional)',
        customer_phone_placeholder: 'Phone (optional)',
        prescription_placeholder: 'If applicable',
        sale_number: 'Sale number',
        date: 'Date',
        no_sales: 'No sales recorded',
        in_stock: 'In stock',
        
        // ========== REPORTS ==========
        reports_title: 'Reports & Exports',
        reports_subtitle: 'Export your data to PDF or Excel',
        inventory: 'Inventory Report',
        inventory_desc: 'Export complete product list with stock, prices and expiration dates.',
        sales_report: 'Sales Report',
        sales_desc: 'Export sales history with transaction details.',
        download_pdf: 'Download PDF',
        download_excel: 'Download Excel',
        start_date: 'Start date',
        end_date: 'End date',
        leave_empty: 'Leave empty to export all sales',
        info_title: 'Export Information',
        info_pdf: 'Print-optimized format',
        info_excel: 'Editable format with summary sheet and detailed data',
        info_filter: 'Sales reports can be filtered by period',
        info_currency: 'All amounts are displayed in Guinean Francs (GNF)',
        download_success: 'File downloaded successfully',
        download_error: 'Error downloading file',
        
        // ========== EMPLOYEES ==========
        employees_title: 'Employee Management',
        employees_subtitle: 'Manage your employees and their permissions',
        add_employee: 'Add employee',
        no_employees: 'No employees. Click "Add employee" to get started.',
        employee: 'Employee',
        contact: 'Contact',
        discipline: 'Discipline',
        permissions: 'Permissions',
        active: 'Active',
        inactive: 'Inactive',
        first_name: 'First name',
        last_name: 'Last name',
        email: 'Email',
        password: 'Password',
        confirm_password: 'Confirm password',
        phone: 'Phone',
        discipline_label: 'Discipline / Specialty',
        pharmacist: 'Pharmacist',
        doctor: 'Doctor',
        nurse: 'Nurse',
        assistant: 'Assistant',
        accountant: 'Accountant',
        other: 'Other',
        permissions_label: 'Permissions',
        manage_stock: 'Stock management',
        make_sales: 'Sales',
        view_reports: 'Reports',
        manage_users: 'User management',
        manage_settings: 'Settings',
        password_mismatch: 'Passwords do not match',
        password_too_short: 'Password must be at least 6 characters',
        employee_added: 'Employee added successfully',
        employee_updated: 'Employee updated successfully',
        employee_deleted: 'Employee deleted successfully',
        email_cannot_change: 'Email cannot be changed',
        activate: 'Activate',
        deactivate: 'Deactivate',
        
        // ========== SETTINGS ==========
        settings_title: 'Settings',
        settings_subtitle: 'Configure your company and user account',
        company: 'Company',
        profile: 'My profile',
        company_info: 'Company information',
        company_name: 'Company name',
        company_phone: 'Phone',
        company_email: 'Email',
        address: 'Address',
        city: 'City',
        postal_code: 'Postal code',
        country: 'Country',
        preferences: 'Preferences',
        currency: 'Currency',
        language: 'Language',
        tax_rate: 'Tax rate (%)',
        invoice_prefix: 'Invoice prefix',
        expiration_alerts: 'Expiration alerts (days)',
        batch_tracking: 'Batch tracking',
        prescription_default: 'Prescription required by default',
        personal_info: 'Personal information',
        role: 'Role',
        update_profile: 'Update profile',
        change_password: 'Change password',
        current_password: 'Current password',
        new_password: 'New password',
        save_success: 'Settings saved successfully',
        profile_updated: 'Profile updated successfully',
        password_changed: 'Password changed successfully',
        current_password_required: 'Please enter your current password',
        new_password_required: 'Please enter a new password',
        owner: 'Owner',
        super_admin: 'Super Admin',
        role_employee: 'Employee',
        expiration_hint: 'Alert X days before expiration',
        
        // ========== SUBSCRIPTION ==========
        subscription_title: 'Subscription',
        subscription_subtitle: 'Manage your subscription and choose the plan that suits your needs',
        current_subscription: 'Your current subscription',
        valid_until: 'Valid until',
        days_remaining: 'Days remaining',
        auto_renew: 'Auto-renewal',
        cancel: 'Cancel',
        choose_plan: 'Choose your plan',
        free: 'Free',
        trial: 'Start trial',
        subscribe: 'Subscribe',
        current_plan: 'Current plan',
        products_max: 'max products',
        employees_max: 'max employees',
        cancel_confirm: 'Cancel your subscription? You can continue until the end of the period.',
        payment_error: 'Error initializing payment',
        days: 'days',
        redirecting: 'Redirecting...',
        stock_basic: 'Basic stock management',
        stock_advanced: 'Advanced stock management',
        sales_basic: 'Basic sales',
        sales_advanced: 'Advanced sales + cart',
        reports_basic: 'Basic reports',
        reports_advanced: 'Advanced reports + charts',
        pdf_exports: 'PDF/Excel export',
        employees_management: 'Employee management',
        advanced_stats: 'Advanced statistics',
        multiple_locations: 'Multiple locations',
        api_access: 'API Access',
        priority_support: 'Priority support',
        
        // ========== COMMON ==========
        cancel_btn: 'Cancel',
        confirm: 'Confirm',
        close: 'Close',
        back: 'Back',
        search_btn: 'Search',
        filter: 'Filter',
        all: 'All',
        yes: 'Yes',
        no: 'No',

        // ========== FOOTER ==========
        footer_description: 'Multi-space pharmaceutical management solution for pharmacies, clinics and hospitals.',
        footer_quick_links: 'Quick links',
        footer_information: 'Information',
        footer_about: 'About',
        footer_privacy: 'Privacy',
        footer_terms: 'Terms of use',
        footer_contact: 'Contact',
        footer_contact_title: 'Contact',
        footer_hours: 'Monday - Friday: 8am - 6pm',
        footer_copyright: 'All rights reserved.',
        footer_version: 'Version',
        footer_developed: 'Developed with',
        footer_for_health: 'for health',


        // ========== PRIVAVACY ==========
        back_to_dashboard: 'Back to dashboard',
        privacy_title: 'Privacy Policy',
        privacy_last_update: 'Last updated',
        privacy_intro_title: 'Introduction',
        privacy_intro_text: 'StockMedi is committed to protecting your personal data. This privacy policy explains what information we collect, how we use it, and how you can control it.',
        privacy_intro_text2: 'By using StockMedi, you agree to the practices described in this document.',
        privacy_data_collected: 'Data collected',
        privacy_data_collected_text: 'We collect the following information:',
        privacy_account: 'Account information',
        privacy_account_text: 'name, first name, email, phone',
        privacy_company: 'Company information',
        privacy_company_text: 'name, address, establishment type',
        privacy_activity: 'Activity data',
        privacy_activity_text: 'products, sales, employees, settings',
        privacy_payment: 'Payment data',
        privacy_payment_text: 'processed by Stripe (we do not store card data)',
        privacy_data_usage: 'Data usage',
        privacy_data_usage_text: 'Your data is used to:',
        privacy_usage_1: 'Manage your account and subscription',
        privacy_usage_2: 'Process your sales and inventory',
        privacy_usage_3: 'Generate your reports',
        privacy_usage_4: 'Improve our services',
        privacy_usage_5: 'Contact you regarding your subscription',
        privacy_data_sharing: 'Data sharing',
        privacy_data_sharing_text: 'We never sell your data to third parties. Your data may be shared with:',
        privacy_sharing_stripe: 'for payments (card data not stored)',
        privacy_sharing_mongodb: 'for secure data hosting',
        privacy_sharing_legal: 'if required by law',
        privacy_security: 'Data security',
        privacy_security_text: 'We implement technical and organizational security measures:',
        privacy_security_1: 'Password encryption (SHA256)',
        privacy_security_2: 'JWT token authentication',
        privacy_security_3: 'HTTPS connection',
        privacy_security_4: 'Restricted data access',
        privacy_retention: 'Data retention',
        privacy_retention_text: 'Your data is kept as long as your account is active. In case of account deletion, your data is anonymized within 30 days, unless required by law.',
        privacy_rights: 'Your rights',
        privacy_rights_text: 'Under GDPR, you have the following rights:',
        privacy_rights_1: 'Right of access to your data',
        privacy_rights_2: 'Right of rectification',
        privacy_rights_3: 'Right to erasure',
        privacy_rights_4: 'Right to data portability',
        privacy_rights_5: 'Right to object',
        privacy_rights_contact: 'To exercise your rights, contact us at:',
        privacy_contact: 'Contact',
        privacy_contact_text: 'For any questions regarding this privacy policy, you can contact us:',
        privacy_changes: 'Policy changes',
        privacy_changes_text: 'We may update this privacy policy. Changes will be posted on this page with an updated date. We will notify you of material changes by email.',
        privacy_footer: 'All rights reserved.',
        privacy_version: 'Version',
        privacy_last_review: 'Last reviewed',
    }
};

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        const saved = localStorage.getItem('language');
        return saved || 'fr';
    });

    const t = (key) => {
        return translations[language][key] || key;
    };

    const changeLanguage = (lang) => {
        setLanguage(lang);
        localStorage.setItem('language', lang);
    };

    return (
        <LanguageContext.Provider value={{ language, t, changeLanguage }}>
            {children}
        </LanguageContext.Provider>
    );
};